config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships, only: [:new, :create, :destroy, :index] do
    post 'confirm', on: :member
  end
  resources :beer_clubs
  resources :users
  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]
  root :to => 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places' => 'places#search'

  resources :styles

  get 'beerlist' => 'beers#list'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  attr_accessible :city, :founded, :name

  scope :unconfirmed, -> {User.joins(:memberships).where(memberships: [confirmed: [nil, false], beer_club_id: id])}

  has_many :memberships
  has_many :members, through: :memberships, source: :user

  def confirmed
    User.joins(:memberships).where('memberships.confirmed' => true,
                                   'memberships.beer_club_id' => id)
    #User.joins(:memberships).where(confirmed: true, beer_club_id: id)
  end

  def unconfirmed
    User.joins(:memberships).where('memberships.confirmed' => false,
                                   'memberships.beer_club_id' => id)
  end

  def application_for(user)
    Membership.where(confirmed: [nil, false], beer_club_id: id, user_id: user.id).first
  end

  def confirmed_member?(user)
    User.joins(:memberships).where(id: user.id,
                                   'memberships.beer_club_id' => id,
                                   'memberships.confirmed' => true)
                            .exists?
  end

  def to_s
    "#{name} (#{city})"
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_filter :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beer_clubs }
    end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @beer_club = BeerClub.find(params[:id])
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @membership.user = current_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer_club }
    end
  end

  # GET /beer_clubs/new
  # GET /beer_clubs/new.json
  def new
    @beer_club = BeerClub.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer_club }
    end
  end

  # GET /beer_clubs/1/edit
  def edit
    @beer_club = BeerClub.find(params[:id])
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(params[:beer_club])

    respond_to do |format|
      if @beer_club.save
        Membership.create(user_id: current_user.id,
                          beer_club_id: @beer_club.id,
                          confirmed: true)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render json: @beer_club, status: :created, location: @beer_club }
      else
        format.html { render action: "new" }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beer_clubs/1
  # PUT /beer_clubs/1.json
  def update
    @beer_club = BeerClub.find(params[:id])

    respond_to do |format|
      if @beer_club.update_attributes(params[:beer_club])
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club = BeerClub.find(params[:id])
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br />
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer_club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Listing beer clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Beer club', new_beer_club_path,
            class: "btn btn-primary" unless current_user.nil? %>

app/views/beer_clubs/new.html.erb
<h1>New beer_club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beer_club.name %>
</p>

<p>
  <b>Founded:</b>
  <%= @beer_club.founded %>
</p>

<p>
  <b>City:</b>
  <%= @beer_club.city %>
</p>

<p>
  <b>Members:</b>
  <ul>
    <% for user in @beer_club.confirmed %>
      <li>
        <%= link_to user, user %>
      </li>
    <% end %>
  </ul>
</p>

<p>
  <% if @beer_club.confirmed_member?(current_user) %>
    <h3>applications</h3>
    <ul>
      <% @beer_club.unconfirmed.each do |u| %>
        <li>
          <%= u.username %>
          <%= link_to "confirm",
                      confirm_membership_path(@beer_club.application_for(u)),
                      method: :post, class: "btn" %>
        </li>
      <% end %>
    </ul>
  <% end %>
</p>

<% unless current_user.nil? or @beer_club.confirmed_member?(current_user) %>
  <p>
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit "Join this club" %>
    <% end %>
  </p>
<% end %>


<% unless current_user.nil? %>
  <%= link_to 'Edit', edit_beer_club_path(@beer_club), class: "btn" %>
  <% if current_user.admin %>
    <%= link_to 'Destroy', @beer_club, method: :delete,
                data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
<% end %>