config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships, only: [:new, :create, :destroy, :index] do
    post 'confirm', on: :member
  end
  resources :beer_clubs
  resources :users
  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :ratings, only: [:index, :new, :create, :destroy]
  root :to => 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :sessions, only: [:new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places' => 'places#search'

  resources :styles

  get 'beerlist' => 'beers#list'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include AverageRating
  extend TopRated
  attr_accessible :name, :year, :active

  scope :active, where(active: true)
  scope :retired, where(active: [nil, false])


  validates_length_of :name, minimum: 1
  validates_numericality_of :year, { greater_than_or_equal_to: 1042,
                                     only_integer: true }
  validates_each :year do |record, attr, value|
    if value > Time.now.year
      record.errors.add(attr, 'cannot be in the future')
    end
  end

  has_many :beers
  has_many :ratings, through: :beers

  def <=> other
    name <=> other.name
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_filter :admin?, only: [:destroy]
  before_filter :ensure_that_signed_in, except: [:index, :show]

  # GET /breweries
  # GET /breweries.json
  def index
    method_names = {'year' => :year, 'name' => :name}
    method = method_names[params[:order]] || :name
    @breweries = Brewery.all.sort_by(&method)

    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @breweries }
    end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/new
  # GET /breweries/new.json
  def new
    @brewery = Brewery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/1/edit
  def edit
    @brewery = Brewery.find(params[:id])
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(params[:brewery])
    expire_fragment action: :index

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render json: @brewery, status: :created, location: @brewery }
      else
        format.html { render action: "new" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breweries/1
  # PUT /breweries/1.json
  def update
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      if @brewery.update_attributes(params[:brewery])
        expire_fragment action: :index
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy
    expire_fragment action: :index

    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    expire_fragment action: :index
    brewery.update_attribute :active, (not brewery.active)
    new_status = if brewery.active then "active" else "retired" end
    redirect_to :back, notice: "brewery activity status changed to #{new_status}"
  end

  private

  def authenticate
    admin_accounts = {"admin" => "secret", "pekka" => "beer",
                      "arto" => "foobar", "matti" => "ittam"}

    authenticate_or_request_with_http_basic do |username, password|
      admin_accounts.has_key?(username) and admin_accounts[username] == password
    end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<% cache do %>
  <h1>Listing breweries</h1>


  <h2>Active</h2>

  <p>number of active breweries <%= @active_breweries.count %></p>
  <%= render 'list', breweries: @active_breweries %>

  <h2>Retired</h2>

  <p>number of retired breweries <%= @retired_breweries.count %></p>
  <%= render 'list', breweries: @retired_breweries %>

  <br />

<% end %>

<%= link_to 'New Brewery', new_brewery_path,
            class: "btn btn-primary"  unless current_user.nil? %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
panimoita <%= @breweries.count %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @brewery.name %>
  <% unless @brewery.active %>
    <span class="label">retired</span>
  <% end %>
</h2>

<p>
  <b>Established year</b>
  <%= @brewery.year %>
</p>

<p>
  number of beers <%= @brewery.beers.count %> <br/>
  <ul>
    <% @brewery.beers.each do |beer| %>
      <li><%= link_to beer.name, beer %></li>
    <% end %>
  </ul>
</p>

<% unless @brewery.ratings.empty? %>
  <p>
    <%= pluralize @brewery.ratings.length, 'rating' %>, average:
    <%= round(@brewery.average_rating) %>
  </p>
<% end %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id),
            method: :post, class: "btn" %>
<%= edit_and_destroy_buttons(@brewery) %>